/**
 * Lead Card Service
 * Implements the "Agentic Transparency" pattern from the B2B Design Skill.
 * Transforms raw lead data and drafts into a high-signal "Lead Card" for owner approval.
 */
const leadCardService = {
  /**
   * Builds a structured Lead Card message.
   * @param {Object} lead - The target business/person data.
   * @param {Object} analysis - The "Why" (synergy, reasoning) generated by the AI.
   * @param {string} draft - The proposed message to be sent.
* @param {string} type - The type of lead ('b2b_qualified', 'b2b_lead', 'supplier', 'customer').
   */
  buildLeadCard(lead, analysis, draft, type = 'b2b_lead') {
    const typeLabels = {
      'b2b_qualified': 'dYOY Qualified B2B (Manifest)',
      'b2b_lead': 'dY"? Discovery Lead',
      'supplier': 'dY"� Supplier Reorder',
      'customer': 'dY`� Customer Follow-up'
    };

    const label = typeLabels[type] || '🎯 New Lead';
    
    // Construct the Card
    let card = `🎯 **${label}**\n`;
    card += `────────────────────\n`;
    card += `👤 **Who:** ${lead.name || 'Unknown'}\n`;
    if (lead.industry) card += `🏢 **Industry:** ${lead.industry}\n`;
    if (lead.location) card += `📍 **Location:** ${lead.location}\n`;
    
    card += `\n💡 **Why (Synergy):**\n${analysis || 'No specific synergy analysis available.'}\n`;
    
    card += `\n📝 **Proposed Draft:**\n\n${draft}\n`;
    card += `────────────────────\n`;
    card += `\n👉 *Reply **YES** to send, or type your changes to edit.*`;

    return card;
  }
};

module.exports = leadCardService;
